### ISSUE TITLE
not an issue but there's no direct messaging on github

### ISSUE THREAD

**Issue by schaefer01** [spacemanspiff2007/sml2mqtt#17]
Hi,
  I was following the issues of a wired mqtt for micropython that had your name and kevinkk525,
    summer 2021.

 https://github.com/peterhinch/micropython-mqtt/issues/56 and 57
  
  I've got a rp feather with a wired ethernet module and need to implement mqtt but not wireless.

  Any progress with this?

thx,
 bob s
 rps@mit.haystack.edu

**Comment by spacemanspiff2007** [comment]
It would have been nice if you had just commented on the original issue and waited for someone to respond.
I'm closing this since this is off topic here.
