### ISSUE TITLE
not possible to use the PIP command at venus OS 

### ISSUE THREAD

**Issue by MartinRe63** [spacemanspiff2007/sml2mqtt#18]
as a result of that we are not able to install your fantastic software. Do you see any option to solve this? Thx.

**Comment by MartinRe63** [comment]
- as a result of that we are not able to install your fantastic software. Do you see any option to solve this? Thx.

**Comment by spacemanspiff2007** [comment]
You can just download the source and the dependency packages and then run it locally with python.

**Comment by spacemanspiff2007** [comment]
closed (stale)
