### ISSUE TITLE
TLS support: not implemented yet?

### ISSUE THREAD

**Issue by hgkdd** [spacemanspiff2007/sml2mqtt#36]
Thanks for the package. I use it to couple my energy meters with home assistant.
Communication without TLS to my mqtt broker works perfectly fine. 

I would like to use TLS for security reasons. But I can't find any information how to specify what ca_cert and client_cert shound be used. 

Is ist correct that TLS is not implented yet? The underlying asyncio_mqtt library seems to support TLS. So, I would guess the implementation is not very hard. Are there any plans to implement this in the near future?

I'm definitely willing to do tests!

**Comment by spacemanspiff2007** [comment]
I've implemented TLS support in the rewrite. Looking forward to your feedback in #39
