### ISSUE TITLE
Support for sml raw input as file?

### ISSUE THREAD

**Issue by MrFr33man123** [spacemanspiff2007/sml2mqtt#37]
As Background info: I have a tibber pulse as smartmeter reader. when webinterface is enabled you can get the raw sml data via curl/wget.
so now i have a file "sml.raw" can i use this as input somehow instead of a url to a device? Just putting the path to the file there does not work. I would setup an other cronjob tu pull the new data and overwrite the file every few seconds.

My first quick look didn't hint me into the right direction.

Thanks :)

**Comment by spacemanspiff2007** [comment]
If you read through #30 you'll see that there is already something that is reading directly from the tibbr pulse device and already working to some degree.
I'd love to get more feedback so I can finally finish the implementation.

**Comment by MrFr33man123** [comment]
Closing this issue as i will participate in #30
